=== UKHomeOffice-attic/lev-api-docs/schema/v0/Birth.json
{
  "$schema": "json-schema.org/draft-04/schema",
  "id": "lev.homeoffice.gov.uk/schema/v0/Birth",
  "type": "object",
  "items": {
    "required": [
      "id",
      "location",
      "previousRegistration",
      "status",
      "subjects"
    ],
    "properties": {
      "date": {
        "type": "string",
        "format": "date",
        "example": "2011-08-09",
        "description": "Date of the event"
      },
      "location": {
        "description": "Location that the event happened at",
        "properties": {
          "name": {
            "type": "string",
            "example": "Manchester, Manchester, Metropolitan District of Manchester",
            "description": "Name"
          },
          "nameQualifier": {
            "type": "string",
            "example": "generated by concatenating registrationDistrict, subDistrict and administrativeArea",
            "description": "Name qualifier"
          },
          "registrationDistrict": {
            "type": "string",
            "example": "Manchester",
            "description": "Registration district"
          },
          "subDistrict": {
            "type": "string",
            "example": "Manchester",
            "description": "Sub-district"
          },
          "administrativeArea": {
            "type": "string",
            "example": "Metropolitan District of Manchester",
            "description": "Administrative area"
          }
        }
      },
      "registrarSignature": {
        "type": "string",
        "example": "J. Smith",
        "description": "Signature of registrar"
      },
      "type": {
        "type": "string",
        "example": "birth",
        "description": "Type of the event"
      },
      "id": {
        "type": "integer",
        "format": "int32",
        "description": "Unique ID for this event"
      },
      "subjects": {
        "description": "People involved, may have keys parent1,parent2,child",
        "properties": {
          "child": {
            "description": "Child",
            "properties": {
              "name": {
                "description": "Name of the person",
                "properties": {
                  "givenName": {
                    "type": "string",
                    "example": "Joan Narcissus Ouroboros",
                    "description": "Given name of the person"
                  },
                  "surname": {
                    "type": "string",
                    "example": "Smith",
                    "description": "Surname of the person"
                  },
                  "fullName": {
                    "type": "string",
                    "example": "Joan Narcissus Ouroboros Smith",
                    "description": "Full name of the person"
                  },
                  "qualifier": {
                    "type": "string",
                    "example": "generated from prepending forename to surname",
                    "description": "Details about how the full name was made"
                  }
                }
              },
              "birthplace": {
                "type": "string",
                "example": "Kensington",
                "description": "The birthplace of the person"
              },
              "dateOfBirth": {
                "type": "string",
                "format": "date",
                "example": "2011-08-08",
                "description": "Date of birth of the person"
              },
              "sex": {
                "type": "string",
                "example": "Indeterminate",
                "description": "Sex of the person",
                "enum": [
                  "Male",
                  "Female",
                  "Indeterminate"
                ]
              },
              "originalName": {
                "description": "The name originally given to the person",
                "properties": {
                  "givenName": {
                    "type": "string",
                    "example": "Joan Narcissus Ouroboros",
                    "description": "Given name of the person"
                  },
                  "surname": {
                    "type": "string",
                    "example": "Smith",
                    "description": "Surname of the person"
                  },
                  "fullName": {
                    "type": "string",
                    "example": "Joan Narcissus Ouroboros Smith",
                    "description": "Full name of the person"
                  },
                  "qualifier": {
                    "type": "string",
                    "example": "generated from prepending forename to surname",
                    "description": "Details about how the full name was made"
                  }
                }
              }
            }
          },
          "father": {
            "description": "Father",
            "properties": {
              "name": {
                "description": "Name of the person",
                "properties": {
                  "givenName": {
                    "type": "string",
                    "example": "Joan Narcissus Ouroboros",
                    "description": "Given name of the person"
                  },
                  "surname": {
                    "type": "string",
                    "example": "Smith",
                    "description": "Surname of the person"
                  },
                  "fullName": {
                    "type": "string",
                    "example": "Joan Narcissus Ouroboros Smith",
                    "description": "Full name of the person"
                  },
                  "qualifier": {
                    "type": "string",
                    "example": "generated from prepending forename to surname",
                    "description": "Details about how the full name was made"
                  }
                }
              },
              "birthplace": {
                "type": "string",
                "example": "Kensington",
                "description": "The birthplace of the person"
              },
              "occupation": {
                "type": "string",
                "example": "Carpenter",
                "description": "The occupation of the parent"
              }
            }
          },
          "mother": {
            "description": "Mother",
            "properties": {
              "name": {
                "description": "Name of the person",
                "properties": {
                  "givenName": {
                    "type": "string",
                    "example": "Joan Narcissus Ouroboros",
                    "description": "Given name of the person"
                  },
                  "surname": {
                    "type": "string",
                    "example": "Smith",
                    "description": "Surname of the person"
                  },
                  "fullName": {
                    "type": "string",
                    "example": "Joan Narcissus Ouroboros Smith",
                    "description": "Full name of the person"
                  },
                  "qualifier": {
                    "type": "string",
                    "example": "generated from prepending forename to surname",
                    "description": "Details about how the full name was made"
                  }
                }
              },
              "birthplace": {
                "type": "string",
                "example": "Kensington",
                "description": "The birthplace of the person"
              },
              "occupation": {
                "type": "string",
                "example": "Carpenter",
                "description": "The occupation of the parent"
              },
              "maidenSurname": {
                "type": "string",
                "example": "Black",
                "description": "Maiden surname"
              },
              "marriageSurname": {
                "type": "string",
                "example": "White",
                "description": "Surname at marriage if different from maiden surname"
              },
              "usualAddress": {
                "type": "string",
                "example": "34 Matriarchs Place, Mumstown, Mumford",
                "description": "Usual address (if different from the place of child's birth)"
              }
            }
          },
          "informant": {
            "description": "Informant",
            "properties": {
              "name": {
                "description": "Name of the person",
                "properties": {
                  "givenName": {
                    "type": "string",
                    "example": "Joan Narcissus Ouroboros",
                    "description": "Given name of the person"
                  },
                  "surname": {
                    "type": "string",
                    "example": "Smith",
                    "description": "Surname of the person"
                  },
                  "fullName": {
                    "type": "string",
                    "example": "Joan Narcissus Ouroboros Smith",
                    "description": "Full name of the person"
                  },
                  "qualifier": {
                    "type": "string",
                    "example": "generated from prepending forename to surname",
                    "description": "Details about how the full name was made"
                  }
                }
              },
              "usualAddress": {
                "type": "string",
                "example": "34 Matriarchs Place, Mumstown, Mumford",
                "description": "The usual address of the person, if different from the mother's"
              },
              "qualification": {
                "type": "string",
                "example": "Mother",
                "description": "The qualification of the informant"
              },
              "signature": {
                "type": "string",
                "example": "J. Smith",
                "description": "The signature of the informant"
              }
            }
          }
        }
      },
      "systemNumber": {
        "type": "integer",
        "format": "int32",
        "description": "System number for this event"
      },
      "status": {
        "description": "Status flags associated with this birth",
        "properties": {
          "blockedRegistration": {
            "type": "boolean",
            "description": "Indicates if data for this record has been blocked"
          },
          "cancelled": {
            "type": "boolean",
            "description": "Indicates if record was cancelled"
          },
          "potentiallyFictitiousBirth": {
            "type": "boolean",
            "description": "Indicates if a birth may be fictitious"
          },
          "reRegistered": {
            "type": "string",
            "description": "Describes if this is a re-registration and why it was needed",
            "enum": [
              "None",
              "Father modified",
              "Father added",
              "Replacement registration",
              "Other",
              "Subsequently married"
            ]
          },
          "correction": {
            "type": "string",
            "description": "Indicates if there has been a correction to this record",
            "enum": [
              "Typographical",
              "Simple clerical",
              "Complex clerical",
              "Error of fact",
              "None"
            ]
          },
          "marginalNote": {
            "type": "string",
            "description": "Gives additional notes on a record",
            "enum": [
              "Re-registered",
              "Court order in place",
              "Court order revoked",
              "Other",
              "None"
            ]
          }
        },
        "required": [
          "blockedRegistration"
        ]
      },
      "previousRegistration": {
        "description": "Details of the previous record, where one exists",
        "properties": {
          "date": {
            "type": "string",
            "format": "date",
            "example": "2011-08-09",
            "description": "Date of the event"
          },
          "systemNumber": {
            "type": "integer",
            "format": "int32",
            "description": "System number for this event"
          }
        }
      }
    },
    "description": "An event that represents a change of state"
  }
}

=== UKHomeOffice-attic/lev-api-docs/mock/__files/body-events-birth-K1D0F.json
[{
  "location": {
    "name": "Test District, Test Subdistrict, Reading",
    "administrativeArea": "Reading",
    "subDistrict": "Test Subdistrict",
    "nameQualifier": "generated by concatenating registrationDistrict, subDistrict and administrativeArea",
    "registrationDistrict": "Test District"
  },
  "subjects": {
    "child": {
      "originalName": {

      },
      "name": {
        "givenName": "Tester",
        "surname": "Solo",
        "fullName": "Tester Solo",
        "qualifier": "generated from prepending forename to surname"
      },
      "dateOfBirth": "2012-02-29",
      "sex": "Male",
      "birthplace": "Test Address"
    },
    "father": {
      "name": {
        "givenName": "Dad",
        "surname": "Solo",
        "fullName": "Dad Solo",
        "qualifier": "generated from prepending forename to surname"
      },
      "birthplace": "Test Birthplace"
    },
    "mother": {
      "name": {
        "givenName": "Mum",
        "surname": "Solo",
        "fullName": "Mum Solo",
        "qualifier": "generated from prepending forename to surname"
      },
      "birthplace": "Test Birthplace",
      "maidenSurname": "prev-Solo",
      "marriageSurname": "prev-M-Solo"
    },
    "informant": {
      "name": {

      },
      "qualification": "Mother",
      "signature": "Mary Manzarek"
    }
  },
  "systemNumber": 999999910,
  "id": 999999910,
  "date": "2014-10-10",
  "status": {
    "potentiallyFictitiousBirth": false,
    "correction": "None",
    "cancelled": false,
    "blockedRegistration": false,
    "marginalNote": "None",
    "reRegistered": "None"
  },
  "previousRegistration": {

  }
}]
